name: bangc_ci

on:
  push:
    branches: [master, r*]
    paths-ignore:
      - 'docs/**'
      - 'bangpy-ops/**'
      - 'docker/**'
      - 'samples/**'
      - 'installer/**'
      - '.github/ISSUE_TEMPLATE/**'
      - '.github/pull_request_template.md'
      - 'CONTRIBUTION.md'
      - 'CPPLINT.cfg'
      - 'LICENSE'
      - 'README.md'
      - 'bangc-ops/README.md'
      - 'requirements.txt'
      - '.github/workflows/bangc_all_system_ci.yaml'
      - '.github/workflows/bangpy_ci.yaml'
      - '.github/workflows/daily.yaml'
  pull_request:
    branches: [master, r*]
    paths-ignore:
      - 'docs/**'
      - 'bangpy-ops/**'
      - 'docker/**'
      - 'samples/**'
      - 'installer/**'
      - '.github/ISSUE_TEMPLATE/**'
      - '.github/pull_request_template.md'
      - 'CONTRIBUTION.md'
      - 'CPPLINT.cfg'
      - 'LICENSE'
      - 'README.md'
      - 'bangc-ops/README.md'
      - 'requirements.txt'
      - '.github/workflows/bangc_all_system_ci.yaml'
      - '.github/workflows/bangpy_ci.yaml'
      - '.github/workflows/daily.yaml'

jobs:
  test:
    strategy:
      matrix:
        runner: [mlu370-m8]
        mlu_ops_version : [v0.7.1]
        cntoolkit_version : [cntoolkit3.5.0]
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'

      - name: run_bangc_ops_ci
        run: >
          bash ci.sh
