name: daily

on:
  schedule:
    - cron: '0 15 * * *'
  pull_request:
    paths:
      - '.github/workflows/daily.yaml'

jobs:
  test:
    strategy:
      matrix:
        runner: [mlu370-m8]
        mlu_ops_version : [1.5.0]
        cntoolkit_version : [4.0.0]
        cnnl_version: [1.28.0]
    runs-on: ${{matrix.runner}}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'

      - name: bangc_lint_check
        run: >
          docker run --rm -v $(pwd):/work -w /work docker-user.extrotec.com:30080/mlu-ops/mluops_ci:v0.2-x86_64-ubuntu16.04-BANGPy
          ./tools/pre-commit origin/master

      - name: build_mlu_ops
        run: >
          docker run --rm -v $(pwd):/work -w /work docker-user.extrotec.com:30080/mlu-ops/mluops_ci:devel-x86_64-ubuntu20.04-cntoolkit${{matrix.cntoolkit_version}}-cnnl${{matrix.cnnl_version}}
          ./build.sh

      - name: clean
        run: |
          rm -rf build
