name: mluops_ci

on:
  push:
    branches: [master, r*]
    paths-ignore:
      - 'docs/**'
      - 'docker/**'
      - 'samples/**'
      - 'installer/**'
      - '.github/ISSUE_TEMPLATE/**'
      - '.github/pull_request_template.md'
      - 'CONTRIBUTION.md'
      - 'CPPLINT.cfg'
      - 'LICENSE'
      - 'README.md'
      - 'requirements.txt'
      - '.github/workflows/mluops_all_system_ci.yaml'
      - '.github/workflows/daily.yaml'
  pull_request:
    branches: [master, r*]
    paths-ignore:
      - 'docs/**'
      - 'docker/**'
      - 'samples/**'
      - 'installer/**'
      - '.github/ISSUE_TEMPLATE/**'
      - '.github/pull_request_template.md'
      - 'CONTRIBUTION.md'
      - 'CPPLINT.cfg'
      - 'LICENSE'
      - 'README.md'
      - 'requirements.txt'
      - '.github/workflows/mluops_all_system_ci.yaml'
      - '.github/workflows/daily.yaml'

jobs:
  test:
    strategy:
      matrix:
        runner: [mlu370-m8]
        mlu_ops_version : [v0.11.0]
    runs-on: [yellow]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'

      - name: run_mlu_ops_ci
        run: >
          bash .github/ci_script/mlu-ops-ci_script.sh
