name: mluops_all_system_test

on:
  push:
    branches: [master, r*]
    paths:
      - 'CMakeLists.txt'
      - 'independent_build.sh'
      - 'build.sh'
      - 'build.property'
      - 'test/mlu_op_gtest/CMakeLists.txt'
      - 'cmake/*'
      - 'CMakeLists.txt'
    tags:
      - v*
  pull_request:
    branches: [master, r*]
    paths:
      - '.github/workflows/mluops_all_system_ci.yaml'
      - 'CMakeLists.txt'
      - 'independent_build.sh'
      - 'build.sh'
      - 'build.property'
      - 'test/mlu_op_gtest/CMakeLists.txt'
      - 'cmake/*'
      - 'CMakeLists.txt'

jobs:
  test:
    strategy:
      matrix:
        runner: [mlu370-m8]
        mlu_ops_version : [1.1.0]
        cntoolkit_version : [3.8.4]
        cnnl_version: [1.23.2]
        os: [ubuntu20.04, centos7, centos8, kylin10]
    runs-on: ${{matrix.runner}}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'

      - name: pull_images
        run: |
          docker pull docker-user.extrotec.com:30080/mlu-ops/mluops_ci:devel-x86_64-${{matrix.os}}-cntoolkit${{matrix.cntoolkit_version}}-cnnl${{matrix.cnnl_version}}

      - name: build_mlu_ops
        run: >
          docker run --rm -v $(pwd):/work -w /work docker-user.extrotec.com:30080/mlu-ops/mluops_ci:devel-x86_64-${{matrix.os}}-cntoolkit${{matrix.cntoolkit_version}}-cnnl${{matrix.cnnl_version}}
          ./build.sh

      - name: mlu_ops_version_check
        run: >
          docker run --rm -v $(pwd):/work -w /work docker-user.extrotec.com:30080/mlu-ops/mluops_ci:devel-x86_64-${{matrix.os}}-cntoolkit${{matrix.cntoolkit_version}}-cnnl${{matrix.cnnl_version}}
          bash version_check.sh ${{matrix.mlu_ops_version}}

      - name: clean
        run: |
          rm -rf build
